### ISSUE TITLE
reset() will call timeout function

### ISSUE THREAD

**Issue by vincent-tr** [Fl4m3Ph03n1x/heartbeatjs#1] opened 2018-03-08 09:44 UTC
Seems that reset() does not work properly :
it calls stop()
then setBeatTimeout that schedule the next timeout regardless of the stopped state
then onTimeout that resets event.timeout, but too late

IMHO setBeatTimeout should take care of the running state before reschedule the next timeout

**Comment by Fl4m3Ph03n1x** [comment] 2018-03-08 18:58
Hello vincent, 

The `reset()` function is meant to use when the heartbeat is not active. As a precaution, I stop any heartbeats before using resetting them to the default stats. 
Such a behavior is intended. 

Can you elaborate on what you would expected from the behavior of `reset`?

**Comment by vincent-tr** [comment] 2018-03-09 09:24
Hi,

Thanks for your reply!

Let me retry to explain what I mean:

Let's take this example:
```
'use strict';

const heartbeatFactory = require('heartbeatjs');

const myHeartBeat = heartbeatFactory();
myHeartBeat.onTimeout(() => console.log('Timeout!'));
myHeartBeat.reset();
```

Here is the output when I run it:
```
$ node test.js
Timeout!
$
```

What I would expect is that the timeout function is not called after I call reset().

Is it a right expectation ?

**Comment by Fl4m3Ph03n1x** [comment] 2018-03-09 11:33
I am inclined towards saying that yes, that would be the expected behavior. Could you provide a MNE ( https://en.wikipedia.org/wiki/Minimal_Working_Example ) so I can further check the code and elaborate on the issue?

**Comment by vincent-tr** [comment] 2018-03-09 12:00
Thanks again for your reply.

You can put my example in a file named `test.js`, then run `npm i heartbeatjs`, and then `node test.js`

Could you reproduce ?

**Comment by Fl4m3Ph03n1x** [comment] 2018-03-10 20:35
I will try it as soon as I can!

**Comment by Fl4m3Ph03n1x** [comment] 2018-03-11 13:27
I have decided to take this opportunity to undergo on a full project revision. I will keep you informed of eventual progress, but be aware this may take some time and I am yet to confirm the behavior you described.

Also, thanks for taking your time to report this issue!

**Comment by Fl4m3Ph03n1x** [comment] 2018-03-28 14:57
Dear @vincent-tr I have found and fixed the origin of the behavior. 

Why was this happening ?
----
It happens that `heartbeatjs` has default values for `TIMEOUT` and `BEAT_INTERVAL`. When you reset the `heartbeat` object, these values applied. 

This makes sense if you have used the heartbeat before and want to reset it. However, if you have never used it before nothing should happen.

What now?
---------
The fix will go live soon, with an update in the documentation, detailing the two DEFAULT values which are currently not documented.

**Comment by Fl4m3Ph03n1x** [comment] 2018-03-29 11:12
The version was now released with updated docs. The issue is fixed.

https://www.npmjs.com/package/heartbeatjs

Thank you for reporting !

**Closed as completed by Fl4m3Ph03n1x** 2018-03-29 11:12 UTC

**Comment by vincent-tr** [comment] 2018-03-29 12:59
Thanks :)
